/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/n3wthTheme.ts
 * Command: astryx theme build src/theme/n3wthTheme.ts
 * CLI: @astryxdesign/cli@0.5.2
 * Core: @astryxdesign/core@0.5.2
 */

/**
 * n3wth theme — built by `npx astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { n3wthTheme } from './n3wth';
 *   import './n3wth.css';
 */
export const n3wthTheme = {
  name: 'n3wth',
  __built: true,
  tokens: {
    "--color-accent": "light-dark(#005CC5, #62D3FF)",
    "--color-accent-muted": "light-dark(color-mix(in srgb, var(--color-accent) 20%, transparent), color-mix(in srgb, var(--color-accent) 25%, transparent))",
    "--color-on-accent": "light-dark(#FFFFFF, #003853)",
    "--color-neutral": "light-dark(#1A1B221A, #D9E4EA33)",
    "--color-background-surface": "light-dark(#ffffff, #101114)",
    "--color-background-body": "light-dark(#ffffff, #08090b)",
    "--color-overlay": "light-dark(#1A1B2266, #141D2199)",
    "--color-overlay-hover": "light-dark(#1A1B220D, #FFFFFF0D)",
    "--color-overlay-pressed": "light-dark(#1A1B221A, #FFFFFF1A)",
    "--color-background-muted": "light-dark(#f5f5f7, #16171b)",
    "--color-text-primary": "light-dark(#1A1B22, #D9E4EA)",
    "--color-text-secondary": "light-dark(#444653, #9CAEB7)",
    "--color-text-disabled": "light-dark(#8E909E, #506169)",
    "--color-text-accent": "var(--color-accent)",
    "--color-icon-accent": "var(--color-accent)",
    "--color-icon-primary": "light-dark(#1A1B22, #D9E4EA)",
    "--color-icon-secondary": "light-dark(#444653, #9CAEB7)",
    "--color-icon-disabled": "light-dark(#8E909E, #506169)",
    "--color-background-card": "light-dark(#ffffff, #101114)",
    "--color-background-popover": "light-dark(#ffffff, #16171b)",
    "--color-background-inverted": "light-dark(#1A1B22, #F6FDFF)",
    "--color-border": "light-dark(#e5e5ea, #22242a)",
    "--color-border-emphasized": "light-dark(#c7c7cc, #33363e)",
    "--color-skeleton": "light-dark(#A8AAB9, #394951)",
    "--color-track": "light-dark(#A8AAB9, #394951)",
    "--color-shadow": "light-dark(#0000001A, #0000004D)",
    "--color-tint-hover": "light-dark(black, white)",
    "--font-size-4xs": "0.375rem",
    "--font-size-3xs": "0.4375rem",
    "--font-size-2xs": "0.5625rem",
    "--font-size-xs": "0.625rem",
    "--font-size-sm": "0.8125rem",
    "--font-size-base": "0.9375rem",
    "--font-size-lg": "1.125rem",
    "--font-size-xl": "1.375rem",
    "--font-size-2xl": "1.625rem",
    "--font-size-3xl": "1.9375rem",
    "--font-size-4xl": "2.3125rem",
    "--font-size-5xl": "2.8125rem",
    "--text-heading-1-size": "var(--font-size-2xl)",
    "--text-heading-1-weight": "var(--font-weight-bold)",
    "--text-heading-1-leading": "1.3846",
    "--text-heading-2-size": "var(--font-size-xl)",
    "--text-heading-2-weight": "var(--font-weight-bold)",
    "--text-heading-2-leading": "1.4545",
    "--text-heading-3-size": "var(--font-size-lg)",
    "--text-heading-3-weight": "var(--font-weight-semibold)",
    "--text-heading-3-leading": "1.5556",
    "--text-heading-4-size": "var(--font-size-base)",
    "--text-heading-4-weight": "var(--font-weight-semibold)",
    "--text-heading-4-leading": "1.6",
    "--text-heading-5-size": "var(--font-size-sm)",
    "--text-heading-5-weight": "var(--font-weight-semibold)",
    "--text-heading-5-leading": "1.5385",
    "--text-heading-6-size": "var(--font-size-xs)",
    "--text-heading-6-weight": "var(--font-weight-semibold)",
    "--text-heading-6-leading": "1.6",
    "--text-body-size": "var(--font-size-base)",
    "--text-body-weight": "var(--font-weight-normal)",
    "--text-body-leading": "1.6",
    "--text-large-size": "var(--font-size-lg)",
    "--text-large-weight": "var(--font-weight-semibold)",
    "--text-large-leading": "1.5556",
    "--text-label-size": "var(--font-size-base)",
    "--text-label-weight": "var(--font-weight-medium)",
    "--text-label-leading": "1.6",
    "--text-code-size": "var(--font-size-base)",
    "--text-code-weight": "var(--font-weight-normal)",
    "--text-code-leading": "1.6",
    "--text-supporting-size": "var(--font-size-sm)",
    "--text-supporting-weight": "var(--font-weight-normal)",
    "--text-supporting-leading": "1.5385",
    "--text-display-1-size": "var(--font-size-5xl)",
    "--text-display-1-weight": "var(--font-weight-normal)",
    "--text-display-1-leading": "1.2444",
    "--text-display-2-size": "var(--font-size-4xl)",
    "--text-display-2-weight": "var(--font-weight-normal)",
    "--text-display-2-leading": "1.2973",
    "--text-display-3-size": "var(--font-size-3xl)",
    "--text-display-3-weight": "var(--font-weight-normal)",
    "--text-display-3-leading": "1.4194",
    "--radius-none": "0px",
    "--radius-inner": "4px",
    "--radius-element": "8px",
    "--radius-container": "12px",
    "--radius-page": "28px",
    "--radius-chat": "28px",
    "--radius-full": "9999px",
    "--duration-fast-min": "115ms",
    "--duration-fast": "150ms",
    "--duration-fast-max": "200ms",
    "--duration-medium-min": "225ms",
    "--duration-medium": "300ms",
    "--duration-medium-max": "400ms",
    "--duration-slow-min": "450ms",
    "--duration-slow": "600ms",
    "--duration-slow-max": "800ms",
    "--font-family-body": "var(--font-geist-sans), -apple-system, system-ui, sans-serif",
    "--font-family-heading": "var(--font-satoshi), var(--font-geist-sans), -apple-system, system-ui, sans-serif",
    "--font-family-code": "var(--font-geist-mono), \"SF Mono\", ui-monospace, monospace"
  },
  components: {
    "heading": {
      "level:1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-1-size)",
        "fontWeight": "var(--text-heading-1-weight)",
        "lineHeight": "var(--text-heading-1-leading)"
      },
      "level:2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-2-size)",
        "fontWeight": "var(--text-heading-2-weight)",
        "lineHeight": "var(--text-heading-2-leading)"
      },
      "level:3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-3-size)",
        "fontWeight": "var(--text-heading-3-weight)",
        "lineHeight": "var(--text-heading-3-leading)"
      },
      "level:4": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-4-size)",
        "fontWeight": "var(--text-heading-4-weight)",
        "lineHeight": "var(--text-heading-4-leading)"
      },
      "level:5": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-5-size)",
        "fontWeight": "var(--text-heading-5-weight)",
        "lineHeight": "var(--text-heading-5-leading)"
      },
      "level:6": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-6-size)",
        "fontWeight": "var(--text-heading-6-weight)",
        "lineHeight": "var(--text-heading-6-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "text": {
      "type:body": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-body-size)",
        "lineHeight": "var(--text-body-leading)"
      },
      "type:large": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-large-size)",
        "lineHeight": "var(--text-large-leading)"
      },
      "type:label": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-label-size)",
        "lineHeight": "var(--text-label-leading)"
      },
      "type:code": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "var(--text-code-size)",
        "lineHeight": "var(--text-code-leading)"
      },
      "type:supporting": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-supporting-size)",
        "lineHeight": "var(--text-supporting-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "button": {
      "base": {
        "borderRadius": "var(--radius-element)",
        "fontWeight": "var(--font-weight-medium)"
      }
    },
    "card": {
      "base": {
        "borderRadius": "var(--radius-container)"
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },

};
