import {defineTheme} from '@astryxdesign/core/theme';

/**
 * n3wth theme — ported from n3wth-garden's n3wthTheme.ts.
 *
 * Satoshi for display and headings, Geist Sans for body, Geist Mono for code.
 * Near-black #08090b page surface. Font files are loaded in globals.css;
 * Astryx only sets the --font-family-* tokens.
 *
 * Built theme files (n3wthTheme.css / n3wthTheme.built.js) are generated by
 * `npx astryx theme build` — never hand-edit them.
 */
export const n3wthTheme = defineTheme({
  name: 'n3wth',

  color: {
    accent: ['#0071e3', '#64d2ff'],
    neutralStyle: 'cool',
    contrast: 'standard',
  },

  typography: {
    scale: {base: 15, ratio: 1.2},
    body: {
      family: 'var(--font-geist-sans)',
      fallbacks: '-apple-system, system-ui, sans-serif',
    },
    heading: {
      family: 'var(--font-satoshi)',
      fallbacks: 'var(--font-geist-sans), -apple-system, system-ui, sans-serif',
      weight: 'semibold',
      weights: {1: 'bold', 2: 'bold'},
    },
    code: {
      family: 'var(--font-geist-mono)',
      fallbacks: '"SF Mono", ui-monospace, monospace',
    },
  },

  radius: {base: 4, multiplier: 1},

  motion: {fast: 150, medium: 300, slow: 600, ratio: 0.75},

  tokens: {
    '--color-background-body': ['#ffffff', '#08090b'],
    '--color-background-surface': ['#ffffff', '#101114'],
    '--color-background-card': ['#ffffff', '#101114'],
    '--color-background-popover': ['#ffffff', '#16171b'],
    '--color-background-muted': ['#f5f5f7', '#16171b'],
    '--color-border': ['#e5e5ea', '#22242a'],
    '--color-border-emphasized': ['#c7c7cc', '#33363e'],
  },

  components: {
    button: {
      base: {
        borderRadius: 'var(--radius-element)',
        fontWeight: 'var(--font-weight-medium)',
      },
    },
    card: {
      base: {
        borderRadius: 'var(--radius-container)',
      },
    },
  },
});
